"""Trade plan queries."""

from __future__ import annotations

from collections.abc import Sequence

from sqlalchemy import Select, func, select
from sqlalchemy.orm import joinedload

from app.core.enums import TradePlanStatus
from app.models.trade_plan import TradePlan
from app.repositories.base import BaseRepository

#: Statuses that represent a plan still governing a decision or a position.
OPEN_STATUSES: frozenset[TradePlanStatus] = frozenset(
    {TradePlanStatus.DRAFT, TradePlanStatus.READY, TradePlanStatus.EXECUTED}
)


class TradePlanRepository(BaseRepository[TradePlan]):
    """Per-user trade plans."""

    model = TradePlan

    def _for_user(self, user_id: int) -> Select[tuple[TradePlan]]:
        """Base statement scoped to one user, with the company loaded."""
        return (
            select(TradePlan)
            .where(TradePlan.user_id == user_id)
            .options(joinedload(TradePlan.company))
        )

    def get_for_user(self, user_id: int, plan_id: int) -> TradePlan | None:
        """Fetch one plan, scoped to its owner."""
        statement = self._for_user(user_id).where(TradePlan.id == plan_id)
        return self.session.scalars(statement).one_or_none()

    def search(
        self,
        user_id: int,
        *,
        status: TradePlanStatus | None = None,
        company_id: int | None = None,
        limit: int = 50,
        offset: int = 0,
    ) -> tuple[Sequence[TradePlan], int]:
        """Paginated plan listing, newest first.

        Ordered by ``created_at`` then ``id``, both descending. The tie-break is
        not cosmetic: ``created_at`` is generated by the database, and SQLite's
        ``CURRENT_TIMESTAMP`` has one-second resolution, so two plans opened in
        the same second would otherwise come back in an arbitrary - and possibly
        different - order on each request.
        """
        statement = self._for_user(user_id)
        if status is not None:
            statement = statement.where(TradePlan.status == status)
        if company_id is not None:
            statement = statement.where(TradePlan.company_id == company_id)

        # Count off a stripped statement: the eager-load option and ORDER BY are
        # pointless work inside a COUNT, and ORDER BY on a subquery is rejected
        # outright by some backends.
        count_statement = select(func.count()).select_from(
            statement.options().order_by(None).subquery()
        )
        total = self.session.scalar(count_statement) or 0
        page = (
            self.session.scalars(
                statement.order_by(TradePlan.created_at.desc(), TradePlan.id.desc())
                .limit(limit)
                .offset(offset)
            )
            .unique()
            .all()
        )
        return page, total

    def list_open_for_user(self, user_id: int) -> Sequence[TradePlan]:
        """Plans in DRAFT, READY or EXECUTED state."""
        statement = self._for_user(user_id).where(TradePlan.status.in_(OPEN_STATUSES))
        return self.session.scalars(statement).unique().all()

    def active_plans_by_company(self, user_id: int) -> dict[int, TradePlan]:
        """The plan currently governing each company the user has a position in.

        ``EXECUTED`` wins over ``READY`` over ``DRAFT`` when a company somehow has
        several, because the executed one is the plan whose stop-loss and target
        actually apply to money at risk.
        """
        priority = {
            TradePlanStatus.EXECUTED: 3,
            TradePlanStatus.READY: 2,
            TradePlanStatus.DRAFT: 1,
        }
        result: dict[int, TradePlan] = {}
        for plan in self.list_open_for_user(user_id):
            incumbent = result.get(plan.company_id)
            if incumbent is None or priority[plan.status] > priority[incumbent.status]:
                result[plan.company_id] = plan
        return result

    def find_committable_plan(self, user_id: int, company_id: int) -> TradePlan | None:
        """A READY plan for this company, if the user has one.

        Used when a trade is recorded without an explicit ``plan_id`` so the trade
        can still be linked to the commitment the user made.
        """
        statement = self._for_user(user_id).where(
            TradePlan.company_id == company_id,
            TradePlan.status == TradePlanStatus.READY,
        )
        return self.session.scalars(statement.order_by(TradePlan.committed_at.desc())).first()
