/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/market-data/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh market data from the active provider
         * @description Reload companies, financial statements and price history.
         *
         *     Existing financials and prices for each company are **replaced**, not merged -
         *     restatements and split-adjusted prices legitimately change history, and a merge
         *     would leave a mix of old and new figures. The commit happens here so a failure
         *     mid-refresh rolls the whole thing back rather than leaving half the market
         *     updated.
         */
        post: operations["sync_market_data_api_v1_admin_market_data_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List alerts
         * @description Stored alerts, newest first.
         *
         *     Read-only: it reports what the last evaluation found. Call
         *     ``POST /alerts/evaluate`` to re-check the portfolio against your rules.
         */
        get: operations["list_alerts_api_v1_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/acknowledge-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dismiss all open alerts
         * @description Dismiss every currently open alert.
         */
        post: operations["acknowledge_all_alerts_api_v1_alerts_acknowledge_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Re-evaluate the portfolio against your rules
         * @description Check every holding against the rules you set for yourself.
         *
         *     Idempotent: running it repeatedly does not duplicate alerts, and conditions that
         *     no longer hold are cleared automatically. Every alert it raises corresponds to
         *     one of your own pre-committed thresholds - a profit target, a stop-loss, a
         *     concentration limit, a review interval - not to a prediction made by this
         *     system.
         */
        post: operations["evaluate_alerts_api_v1_alerts_evaluate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/{alert_id}/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dismiss one alert
         * @description Dismiss an alert. The row is kept as part of your decision journal.
         */
        post: operations["acknowledge_alert_api_v1_alerts__alert_id__acknowledge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List companies
         * @description Browse the companies available for analysis.
         */
        get: operations["list_companies_api_v1_companies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get one company
         * @description One company with its stored annual figures, exactly as reported.
         *
         *     Derived ratios are deliberately not included here - see the fundamentals
         *     endpoint, which explains and judges them.
         */
        get: operations["get_company_api_v1_companies__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{symbol}/fundamentals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run the fundamentals checklist
         * @description Score a company against the guide's fundamentals checklist.
         *
         *     Returns a verdict per metric, the four-question statement review, any red
         *     flags, and counts of how many criteria are met. It does not return a rating,
         *     a price target or a buy/sell signal, and it never will - see
         *     ``docs/ARCHITECTURE.md`` on why that constraint is treated as a requirement.
         */
        get: operations["get_fundamentals_api_v1_companies__symbol__fundamentals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{symbol}/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get price history
         * @description Daily OHLCV bars, oldest first.
         */
        get: operations["get_price_history_api_v1_companies__symbol__prices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{symbol}/technicals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get technical readings
         * @description Trend, RSI, moving averages and volume confirmation for one company.
         *
         *     The user's declared time horizon is read from their profile purely to frame
         *     the result: the guide's point is that a bearish reading matters far less to a
         *     five-year holder than to a short-term trader. The numbers are identical either
         *     way.
         */
        get: operations["get_technicals_api_v1_companies__symbol__technicals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness and dependency check
         * @description Report whether the service and its database are usable.
         *
         *     Runs a real ``SELECT 1``: a health check that only proves the process is
         *     running will report healthy while every request fails on a dead connection
         *     pool.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server vocabulary and data provenance
         * @description Enumerations, labels and the active market data provider.
         *
         *     Clients should render forms from this response rather than hard-coding option
         *     lists, and **must** honour ``provider.is_synthetic`` by labelling generated
         *     figures as such.
         */
        get: operations["metadata_api_v1_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List trade plans
         * @description Plans newest first, optionally filtered by status.
         */
        get: operations["list_plans_api_v1_plans_get"];
        put?: never;
        /**
         * Start a trade plan
         * @description Open a draft plan for a company.
         *
         *     Everything except the symbol is optional at this point - the plan is meant to
         *     be worked through, and the response's ``readiness`` field lists exactly what is
         *     still missing before it can be committed to.
         */
        post: operations["create_plan_api_v1_plans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a trade plan
         * @description One plan with its readiness assessment, position sizing and review journal.
         */
        get: operations["get_plan_api_v1_plans__plan_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a draft plan
         * @description Answer checklist questions, or set the thesis and exit rules.
         *
         *     Only draft plans are editable. Once a plan has been committed to it is a record
         *     of a decision, and editing it would rewrite the history the review journal
         *     exists to preserve.
         */
        patch: operations["update_plan_api_v1_plans__plan_id__patch"];
        trace?: never;
    };
    "/api/v1/plans/{plan_id}/abandon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Abandon a plan
         * @description Record that you decided not to buy after all.
         *
         *     The plan is kept, not deleted: a decision not to act, and the reason for it, is
         *     worth re-reading the next time the same idea comes around.
         */
        post: operations["abandon_plan_api_v1_plans__plan_id__abandon_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{plan_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Close an executed plan
         * @description Mark a plan closed once the position it governed has been exited.
         */
        post: operations["close_plan_api_v1_plans__plan_id__close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{plan_id}/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Commit to a plan
         * @description Move a plan from draft to ready.
         *
         *     Rejected unless all five pre-buy questions are answered "yes" **and** both a
         *     profit target and a stop-loss are set. That is the one hard rule in this
         *     application: the guide's instruction is to decide the exit before buying, not
         *     while watching the price move.
         */
        post: operations["commit_plan_api_v1_plans__plan_id__commit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{plan_id}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record a thesis check-in
         * @description Record that you re-checked why you own this, and what you concluded.
         *
         *     This is the guide's "thesis check-in": if the reason you bought has changed,
         *     that is a far stronger signal than a red candle on a chart. Recording a review
         *     clears the review-due alert, which is why a substantive note is required.
         */
        post: operations["record_review_api_v1_plans__plan_id__reviews_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the portfolio
         * @description Current holdings, valued at the latest stored close.
         *
         *     Holdings are rebuilt from the trade ledger on every request rather than read
         *     from a holdings table, so they can never disagree with the trades that produced
         *     them. ``market_data_is_synthetic`` tells the client whether the prices behind
         *     these valuations are real - the UI must label them when they are not.
         */
        get: operations["get_portfolio_api_v1_portfolio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolio/trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List recorded trades
         * @description The trade ledger, newest first.
         */
        get: operations["list_trades_api_v1_portfolio_trades_get"];
        put?: never;
        /**
         * Record a trade
         * @description Append a buy or sell to the ledger.
         *
         *     A buy against a plan that is READY marks that plan EXECUTED: the commitment has
         *     been acted on, and its profit target and stop-loss now govern real money. If no
         *     ``plan_id`` is supplied, a READY plan for the same company is linked
         *     automatically.
         */
        post: operations["record_trade_api_v1_portfolio_trades_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the investor profile
         * @description Your recorded goals, risk limits and money-hygiene declarations.
         *
         *     Returns ``204 No Content`` when no profile exists, rather than a 404 or an
         *     object of defaults. A 404 would suggest something is broken, and returning
         *     defaults would let the user believe they had already written down goals they
         *     never chose - the first thing the guide asks them to do.
         */
        get: operations["get_profile_api_v1_profile_get"];
        /**
         * Create or replace the investor profile
         * @description Write down your time horizon, risk tolerance and position limits.
         *
         *     A full replacement rather than a patch: the guide's instruction is to decide all
         *     of this together, before looking at any company. The response includes derived
         *     warnings - for example if no emergency fund is recorded, or if the stated risk
         *     tolerance and drawdown tolerance contradict each other.
         */
        put: operations["upsert_profile_api_v1_profile_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watchlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List watched companies
         * @description Companies you are researching, with a current price snapshot on each.
         *
         *     ``entry_price_reached`` and ``distance_to_target_pct`` are computed against the
         *     latest stored close, so the client does not have to replicate the arithmetic.
         */
        get: operations["list_watchlist_api_v1_watchlist_get"];
        put?: never;
        /**
         * Watch a company
         * @description Add a company to the watchlist.
         *
         *     A research note is required. The guide's first listed mistake is chasing hype,
         *     and having to write down *why* before the app will track something is the
         *     cheapest available guard against it.
         */
        post: operations["add_watchlist_item_api_v1_watchlist_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watchlist/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Stop watching a company
         * @description Remove a company from the watchlist.
         */
        delete: operations["remove_watchlist_item_api_v1_watchlist__item_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update a watchlist entry
         * @description Revise the research note or the entry price you are waiting for.
         */
        patch: operations["update_watchlist_item_api_v1_watchlist__item_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AlertEvaluationResult
         * @description Outcome of running the portfolio monitor.
         *
         *     Returned by the explicit evaluate endpoint so the UI can say "3 new, 2 already
         *     known" instead of silently refreshing a list.
         */
        AlertEvaluationResult: {
            /** Alerts */
            alerts: components["schemas"]["AlertRead"][];
            /** Already Open */
            already_open: number;
            /** Created */
            created: number;
            /**
             * Note
             * @default Every alert here is one of your own pre-committed rules crossing its threshold. None of them is a recommendation to act.
             */
            note: string;
            /**
             * Resolved
             * @description Previously raised alerts whose condition no longer holds; these are acknowledged automatically.
             */
            resolved: number;
        };
        /**
         * AlertKind
         * @description Reasons the portfolio monitor raises an alert.
         *
         *     Each is a *pre-committed rule the user wrote themselves* firing - not a
         *     recommendation generated by the system.
         * @enum {string}
         */
        AlertKind: "profit_target_reached" | "stop_loss_breached" | "thesis_review_due" | "position_concentration" | "sector_concentration" | "watchlist_entry_price_reached" | "fundamental_red_flag";
        /**
         * AlertRead
         * @description A single alert.
         */
        AlertRead: {
            /** Acknowledged At */
            acknowledged_at?: string | null;
            /** Company Id */
            company_id?: number | null;
            /** Company Name */
            company_name?: string | null;
            /** Context */
            context?: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /**
             * Is Acknowledged
             * @default false
             */
            is_acknowledged: boolean;
            kind: components["schemas"]["AlertKind"];
            /** Message */
            message: string;
            severity: components["schemas"]["AlertSeverity"];
            /** Symbol */
            symbol?: string | null;
        };
        /**
         * AlertSeverity
         * @description How loudly an alert should be surfaced in the UI.
         * @enum {string}
         */
        AlertSeverity: "info" | "warning" | "critical";
        /**
         * AnnualFinancialsRead
         * @description Reported figures for one fiscal year, exactly as stored.
         *
         *     Derived measures are deliberately absent - they belong to the fundamentals
         *     report, which explains and judges them. This endpoint is the raw record, so a
         *     user can reconcile it against the annual report.
         */
        AnnualFinancialsRead: {
            /** Capital Expenditure */
            capital_expenditure?: string | null;
            /** Dividend Per Share */
            dividend_per_share?: string | null;
            /** Eps */
            eps?: string | null;
            /** Fiscal Year */
            fiscal_year: number;
            /** Net Profit */
            net_profit?: string | null;
            /** Operating Cash Flow */
            operating_cash_flow?: string | null;
            /** Revenue */
            revenue?: string | null;
            /** Shares Outstanding */
            shares_outstanding?: string | null;
            /** Source */
            source?: string | null;
            /** Total Assets */
            total_assets?: string | null;
            /** Total Debt */
            total_debt?: string | null;
            /** Total Equity */
            total_equity?: string | null;
        };
        /** Body_abandon_plan_api_v1_plans__plan_id__abandon_post */
        Body_abandon_plan_api_v1_plans__plan_id__abandon_post: {
            /**
             * Reason
             * @description Why you decided not to buy. Recorded in the plan's journal.
             */
            reason?: string | null;
        };
        /**
         * ChecklistItemRead
         * @description One pre-buy question and the user's answer.
         */
        ChecklistItemRead: {
            /**
             * Answer
             * @description Null means unanswered, which is not the same as 'no'.
             */
            answer?: boolean | null;
            /** Key */
            key: string;
            /** Question */
            question: string;
        };
        /**
         * CompanyDetail
         * @description Single-company view, including the raw statements.
         */
        CompanyDetail: {
            /** Business Summary */
            business_summary?: string | null;
            /** Financials */
            financials?: components["schemas"]["AnnualFinancialsRead"][];
            /** Fiscal Years */
            fiscal_years?: number[];
            /**
             * Has Financials
             * @default false
             */
            has_financials: boolean;
            /**
             * Has Price History
             * @default false
             */
            has_price_history: boolean;
            /** Id */
            id: number;
            /** Is Active */
            is_active: boolean;
            /**
             * Last Close
             * @description Most recent close held locally, if any.
             */
            last_close?: string | null;
            /** Last Close Date */
            last_close_date?: string | null;
            /** Name */
            name: string;
            sector: components["schemas"]["Sector"];
            /** Sector Label */
            sector_label: string;
            /** Symbol */
            symbol: string;
            /** Website */
            website?: string | null;
        };
        /**
         * CompanySummary
         * @description List-view representation of a company.
         */
        CompanySummary: {
            /**
             * Has Financials
             * @default false
             */
            has_financials: boolean;
            /**
             * Has Price History
             * @default false
             */
            has_price_history: boolean;
            /** Id */
            id: number;
            /** Is Active */
            is_active: boolean;
            /**
             * Last Close
             * @description Most recent close held locally, if any.
             */
            last_close?: string | null;
            /** Last Close Date */
            last_close_date?: string | null;
            /** Name */
            name: string;
            sector: components["schemas"]["Sector"];
            /** Sector Label */
            sector_label: string;
            /** Symbol */
            symbol: string;
        };
        /**
         * ConcentrationWarning
         * @description A breach of one of the user's declared diversification limits.
         */
        ConcentrationWarning: {
            /**
             * Kind
             * @description 'position' or 'sector'.
             */
            kind: string;
            /** Limit Pct */
            limit_pct: string;
            /** Message */
            message: string;
            /**
             * Subject
             * @description Symbol or sector label the warning is about.
             */
            subject: string;
            /** Weight Pct */
            weight_pct: string;
        };
        /**
         * Disclaimer
         * @description Standing disclaimer attached to every analytical response.
         *
         *     Kept in the payload rather than only in the UI so that the caveat travels
         *     with the data - if a screenshot, export or third-party client consumes this
         *     API, the caveat is part of what it consumed.
         */
        Disclaimer: {
            /**
             * Is Financial Advice
             * @description Always false. This API scores stated criteria; it does not advise.
             * @default false
             */
            is_financial_advice: boolean;
            /**
             * Text
             * @default Educational and general in nature. These figures score a company against a fixed checklist and do not predict price movements. Nothing here is financial advice, and no checklist guarantees profit or protects against loss. Consider a licensed financial advisor for your own situation.
             */
            text: string;
        };
        /**
         * EnumOption
         * @description A single allowed value with its display label.
         */
        EnumOption: {
            /** Description */
            description?: string | null;
            /** Label */
            label: string;
            /** Value */
            value: string;
        };
        /**
         * FundamentalsReport
         * @description Full output of the fundamentals checklist for one company.
         */
        FundamentalsReport: {
            /** Company Name */
            company_name: string;
            /**
             * @default {
             *       "is_financial_advice": false,
             *       "text": "Educational and general in nature. These figures score a company against a fixed checklist and do not predict price movements. Nothing here is financial advice, and no checklist guarantees profit or protects against loss. Consider a licensed financial advisor for your own situation."
             *     }
             */
            disclaimer: components["schemas"]["Disclaimer"];
            /** Fiscal Years */
            fiscal_years: number[];
            /** Latest Fiscal Year */
            latest_fiscal_year: number;
            /** Metrics */
            metrics: components["schemas"]["MetricAssessment"][];
            /**
             * Peer Count
             * @description Sector peers with usable data, used for median comparisons.
             * @default 0
             */
            peer_count: number;
            /** Red Flags */
            red_flags: components["schemas"]["RedFlag"][];
            /** Reference Price */
            reference_price?: number | null;
            /** Reference Price Date */
            reference_price_date?: string | null;
            score: components["schemas"]["FundamentalsScore"];
            sector: components["schemas"]["Sector"];
            /** Sector Label */
            sector_label: string;
            statement_review: components["schemas"]["StatementReview"];
            /** Symbol */
            symbol: string;
        };
        /**
         * FundamentalsScore
         * @description Aggregate view of the checklist.
         *
         *     Exposed as counts rather than a single 0-100 grade on purpose. A composite
         *     score invites exactly the behaviour the guide warns against - treating one
         *     number as a verdict - and hides which criteria failed.
         */
        FundamentalsScore: {
            /** Adequate */
            adequate: number;
            /** Insufficient Data */
            insufficient_data: number;
            /** Metrics Assessed */
            metrics_assessed: number;
            /**
             * Note
             * @default Counts of how many checklist criteria this company currently meets. This is not a rating, a price target, or a buy/sell signal.
             */
            note: string;
            /** Strong */
            strong: number;
            /** Weak */
            weak: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthRead
         * @description Liveness and dependency check.
         */
        HealthRead: {
            /** Database Reachable */
            database_reachable: boolean;
            /** Environment */
            environment: string;
            /**
             * Status
             * @description 'ok' or 'degraded'.
             */
            status: string;
            /** Version */
            version: string;
        };
        /**
         * HoldingRead
         * @description An open position, valued at the latest stored close.
         *
         *     Derived from the trade ledger on every read - there is no holdings table. See
         *     the module docstring of :mod:`app.models.trade` for why.
         */
        HoldingRead: {
            /**
             * Average Cost
             * @description Cost basis per share, including buy-side fees.
             */
            average_cost: string;
            /** Company Id */
            company_id: number;
            /** Company Name */
            company_name: string;
            /**
             * Cost Basis
             * @description Total invested in the shares still held.
             */
            cost_basis: string;
            /**
             * Distance To Stop Pct
             * @description How far the price would have to fall to breach the stop.
             */
            distance_to_stop_pct?: string | null;
            /**
             * Distance To Target Pct
             * @description How far the price must rise to reach the profit target.
             */
            distance_to_target_pct?: string | null;
            /** Last Price */
            last_price?: string | null;
            /** Last Price Date */
            last_price_date?: string | null;
            /** Last Reviewed At */
            last_reviewed_at?: string | null;
            /** Market Value */
            market_value?: string | null;
            /**
             * Missing Exit Rules
             * @default true
             */
            missing_exit_rules: boolean;
            /** Plan Id */
            plan_id?: number | null;
            /** Profit Target Price */
            profit_target_price?: string | null;
            /** Quantity */
            quantity: string;
            /**
             * Realised Pl
             * @description Profit already banked on shares sold from this position, net of fees.
             * @default 0
             */
            realised_pl: string;
            sector: components["schemas"]["Sector"];
            /** Sector Label */
            sector_label: string;
            /** Stop Loss Price */
            stop_loss_price?: string | null;
            /** Symbol */
            symbol: string;
            /** Unrealised Pl */
            unrealised_pl?: string | null;
            /** Unrealised Pl Pct */
            unrealised_pl_pct?: string | null;
            /**
             * Weight Pct
             * @description Share of total portfolio market value.
             */
            weight_pct?: string | null;
        };
        /**
         * IndicatorReading
         * @description A single technical indicator with its interpretation.
         */
        IndicatorReading: {
            /** Commentary */
            commentary: string;
            /** Key */
            key: string;
            /** Label */
            label: string;
            /**
             * State
             * @description Descriptive state, e.g. 'uptrend', 'overbought'.
             */
            state: string;
            /** Unit */
            unit?: string | null;
            /** Value */
            value?: number | null;
            /** What It Measures */
            what_it_measures: string;
        };
        /**
         * InvestorProfileRead
         * @description The stored plan, plus any warnings it implies.
         */
        InvestorProfileRead: {
            /** Drawdown Tolerance Pct */
            drawdown_tolerance_pct: string;
            /** Emergency Fund In Place */
            emergency_fund_in_place: boolean;
            /** Goals Note */
            goals_note?: string | null;
            /** Investable Capital */
            investable_capital: string;
            /** Investing Borrowed Money */
            investing_borrowed_money: boolean;
            /** Max Position Pct */
            max_position_pct: string;
            /** Max Sector Pct */
            max_sector_pct: string;
            /** Review Interval Days */
            review_interval_days: number;
            risk_tolerance: components["schemas"]["RiskTolerance"];
            time_horizon: components["schemas"]["TimeHorizon"];
            /** Warnings */
            warnings?: string[];
        };
        /**
         * InvestorProfileUpsert
         * @description Create or replace the investor's plan.
         *
         *     Modelled as a full replacement (PUT) rather than a patch: this document is
         *     short, and the guide's instruction is to write the whole thing down before
         *     buying anything. A partial update would let a user quietly raise their own
         *     risk limit without re-reading the rest.
         */
        InvestorProfileUpsert: {
            /**
             * Drawdown Tolerance Pct
             * @description The drop you could hold through without selling in a panic.
             * @default 30
             */
            drawdown_tolerance_pct: number | string;
            /**
             * Emergency Fund In Place
             * @default false
             */
            emergency_fund_in_place: boolean;
            /** Goals Note */
            goals_note?: string | null;
            /**
             * Investable Capital
             * @description Money you can afford to have tied up or lose. Not rent or emergency funds.
             * @default 0
             */
            investable_capital: number | string;
            /**
             * Investing Borrowed Money
             * @default false
             */
            investing_borrowed_money: boolean;
            /**
             * Max Position Pct
             * @description Largest share of the portfolio any single holding may take.
             * @default 15
             */
            max_position_pct: number | string;
            /**
             * Max Sector Pct
             * @description Largest share of the portfolio any single sector may take.
             * @default 35
             */
            max_sector_pct: number | string;
            /**
             * Review Interval Days
             * @description How often to revisit the reason you own each holding.
             * @default 90
             */
            review_interval_days: number;
            risk_tolerance: components["schemas"]["RiskTolerance"];
            time_horizon: components["schemas"]["TimeHorizon"];
        };
        /**
         * MessageResponse
         * @description Simple acknowledgement for endpoints with nothing better to return.
         */
        MessageResponse: {
            /** Message */
            message: string;
        };
        /**
         * MetadataRead
         * @description Everything the client needs to render forms and labels consistently.
         */
        MetadataRead: {
            /**
             * @default {
             *       "is_financial_advice": false,
             *       "text": "Educational and general in nature. These figures score a company against a fixed checklist and do not predict price movements. Nothing here is financial advice, and no checklist guarantees profit or protects against loss. Consider a licensed financial advisor for your own situation."
             *     }
             */
            disclaimer: components["schemas"]["Disclaimer"];
            /** Metric Verdicts */
            metric_verdicts: components["schemas"]["EnumOption"][];
            /** Prebuy Checklist */
            prebuy_checklist: components["schemas"]["EnumOption"][];
            provider: components["schemas"]["ProviderInfo"];
            /** Risk Tolerances */
            risk_tolerances: components["schemas"]["EnumOption"][];
            /** Sectors */
            sectors: components["schemas"]["EnumOption"][];
            /** Time Horizons */
            time_horizons: components["schemas"]["EnumOption"][];
        };
        /**
         * MetricAssessment
         * @description One row of the fundamentals checklist.
         */
        MetricAssessment: {
            /**
             * Commentary
             * @description How this company reads against the criteria.
             */
            commentary: string;
            /** Criteria */
            criteria: string;
            /** History */
            history?: components["schemas"]["YearValue"][];
            /**
             * Key
             * @description Stable machine name, e.g. 'net_margin'.
             */
            key: string;
            /**
             * Label
             * @description Display name, e.g. 'Net profit margin'.
             */
            label: string;
            /**
             * Peer Median
             * @description Median of the same metric across sector peers, when a comparison was used.
             */
            peer_median?: number | null;
            /**
             * Unit
             * @description Unit of `value`: '%', 'x', 'PKR' or null for a count.
             */
            unit?: string | null;
            /**
             * Value
             * @description Headline number for the metric; null when not computable.
             */
            value?: number | null;
            verdict: components["schemas"]["MetricVerdict"];
            /** What It Measures */
            what_it_measures: string;
        };
        /**
         * MetricVerdict
         * @description Quality of a single fundamental metric against the guide's criteria.
         * @enum {string}
         */
        MetricVerdict: "strong" | "adequate" | "weak" | "insufficient_data";
        /**
         * MovingAveragePosition
         * @description Where price sits relative to the 50-day and 200-day moving averages.
         * @enum {string}
         */
        MovingAveragePosition: "above_both" | "mixed" | "below_both" | "unknown";
        /** Page[CompanySummary] */
        Page_CompanySummary_: {
            /** Items */
            items: components["schemas"]["CompanySummary"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /**
             * Total
             * @description Total number of matching rows, ignoring pagination.
             */
            total: number;
        };
        /** Page[TradePlanRead] */
        Page_TradePlanRead_: {
            /** Items */
            items: components["schemas"]["TradePlanRead"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /**
             * Total
             * @description Total number of matching rows, ignoring pagination.
             */
            total: number;
        };
        /**
         * PlanReviewRead
         * @description One recorded thesis check-in.
         */
        PlanReviewRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Note */
            note: string;
            /** Thesis Still Valid */
            thesis_still_valid: boolean;
        };
        /**
         * PortfolioRead
         * @description Everything the portfolio screen needs in one response.
         */
        PortfolioRead: {
            /** Concentration Warnings */
            concentration_warnings: components["schemas"]["ConcentrationWarning"][];
            /** Holdings */
            holdings: components["schemas"]["HoldingRead"][];
            /**
             * Market Data Is Synthetic
             * @description True when prices come from the generated demo dataset.
             */
            market_data_is_synthetic: boolean;
            /** Sector Allocations */
            sector_allocations: components["schemas"]["SectorAllocation"][];
            summary: components["schemas"]["PortfolioSummary"];
            /** Valued At */
            valued_at?: string | null;
        };
        /**
         * PortfolioSummary
         * @description Aggregate portfolio position.
         */
        PortfolioSummary: {
            /** Diversification Note */
            diversification_note: string;
            /** Holdings Count */
            holdings_count: number;
            /**
             * Holdings Without Exit Rules
             * @default 0
             */
            holdings_without_exit_rules: number;
            /** Sectors Held */
            sectors_held: number;
            /** Total Cost Basis */
            total_cost_basis: string;
            /** Total Fees Paid */
            total_fees_paid: string;
            /** Total Market Value */
            total_market_value: string;
            /**
             * Total Realised Pl
             * @description Banked profit or loss across all closed and partially closed positions.
             */
            total_realised_pl: string;
            /** Total Unrealised Pl */
            total_unrealised_pl: string;
            /** Total Unrealised Pl Pct */
            total_unrealised_pl_pct?: string | null;
        };
        /**
         * PositionSizingCheck
         * @description Whether the intended purchase respects the user's own position limit.
         */
        PositionSizingCheck: {
            /** Commentary */
            commentary: string;
            /** Exceeds Limit */
            exceeds_limit?: boolean | null;
            /** Intended Amount */
            intended_amount?: string | null;
            /** Max Position Pct */
            max_position_pct: string;
            /**
             * Portfolio Value
             * @description Current market value of holdings, used as the sizing base.
             */
            portfolio_value: string;
            /** Resulting Weight Pct */
            resulting_weight_pct?: string | null;
            /**
             * Sizing Base
             * @description The base the limit was applied to: the larger of portfolio value and declared investable capital, so the first purchase in an empty portfolio is still sized against a real number.
             */
            sizing_base: string;
            /** Suggested Max Amount */
            suggested_max_amount: string;
        };
        /**
         * PriceBarRead
         * @description One trading session.
         */
        PriceBarRead: {
            /** Close */
            close: string;
            /** High */
            high: string;
            /** Low */
            low: string;
            /** Open */
            open: string;
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
            /** Volume */
            volume: number;
        };
        /**
         * PriceHistoryRead
         * @description A company's stored price series.
         */
        PriceHistoryRead: {
            /** Bars */
            bars: components["schemas"]["PriceBarRead"][];
            /** Sessions */
            sessions: number;
            /** Symbol */
            symbol: string;
        };
        /**
         * ProviderInfo
         * @description Which market data provider is active, and whether to trust its numbers.
         */
        ProviderInfo: {
            /** Description */
            description: string;
            /**
             * Is Synthetic
             * @description True when figures are generated for demonstration. The UI must label the data accordingly and must not present it as real market data.
             */
            is_synthetic: boolean;
            /** Name */
            name: string;
            /**
             * Verification Sources
             * @description Where to check real figures yourself (guide section 8).
             */
            verification_sources?: string[];
        };
        /**
         * RedFlag
         * @description A specific, evidenced concern - not a generic warning.
         */
        RedFlag: {
            /** Detail */
            detail: string;
            /** Key */
            key: string;
            /**
             * Severity
             * @description 'info', 'warning' or 'critical'.
             */
            severity: string;
            /** Title */
            title: string;
        };
        /**
         * RiskTolerance
         * @description Self-assessed tolerance for drawdown.
         * @enum {string}
         */
        RiskTolerance: "conservative" | "moderate" | "aggressive";
        /**
         * RsiZone
         * @description Relative Strength Index bands as described in the guide (30 / 70).
         * @enum {string}
         */
        RsiZone: "oversold" | "neutral" | "overbought" | "unknown";
        /**
         * Sector
         * @description PSX sectors used for peer comparison and diversification checks.
         *
         *     Deliberately coarse: the guide's advice is to compare P/E and debt against
         *     peers "in the same sector" and to diversify across sectors such as banks,
         *     cement, oil & gas, fertilizer and consumer goods.
         * @enum {string}
         */
        Sector: "commercial_banks" | "cement" | "oil_and_gas" | "fertilizer" | "food_and_personal_care" | "power_generation" | "textile_composite" | "automobile_assembler" | "technology_and_communication" | "pharmaceuticals" | "chemical" | "other";
        /**
         * SectorAllocation
         * @description Portfolio weight in one sector, against the user's own limit.
         */
        SectorAllocation: {
            /**
             * Exceeds Limit
             * @default false
             */
            exceeds_limit: boolean;
            /** Holdings Count */
            holdings_count: number;
            /** Market Value */
            market_value: string;
            sector: components["schemas"]["Sector"];
            /** Sector Label */
            sector_label: string;
            /** Weight Pct */
            weight_pct: string;
        };
        /**
         * StatementCheck
         * @description One of the four plain-language questions from guide section 3.
         */
        StatementCheck: {
            /** Detail */
            detail: string;
            /** Key */
            key: string;
            /**
             * Passed
             * @description Null when the underlying figures are unavailable.
             */
            passed?: boolean | null;
            /** Question */
            question: string;
        };
        /**
         * StatementReview
         * @description The four-question sanity check over the three financial statements.
         *
         *     The guide's rule is quoted directly: if two or more answers are "no", that is
         *     worth investigating before buying. This object reports that condition; it
         *     does not turn it into a recommendation.
         */
        StatementReview: {
            /** Checks */
            checks: components["schemas"]["StatementCheck"][];
            /** Failed Count */
            failed_count: number;
            /**
             * Needs Investigation
             * @description True when two or more of the four checks answered 'no'.
             */
            needs_investigation: boolean;
            /** Summary */
            summary: string;
            /** Unknown Count */
            unknown_count: number;
        };
        /**
         * SyncResultRead
         * @description What a market data refresh changed.
         */
        SyncResultRead: {
            /** Companies Created */
            companies_created: number;
            /** Companies Updated */
            companies_updated: number;
            /** Financial Years Written */
            financial_years_written: number;
            /** Price Bars Written */
            price_bars_written: number;
            /** Provider */
            provider: string;
            /** Provider Is Synthetic */
            provider_is_synthetic: boolean;
            /** Symbols Skipped */
            symbols_skipped: string[];
        };
        /**
         * TechnicalReport
         * @description Timing context for a company - explicitly not a reason to buy or sell.
         *
         *     The guide is unambiguous that indicators are inputs, not verdicts, and that a
         *     bearish reading on a fundamentally strong stock held for years matters far
         *     less than the same reading on a short-term trade. :attr:`horizon_note`
         *     carries that framing into the payload, personalised to the user's declared
         *     time horizon when one is available.
         */
        TechnicalReport: {
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /**
             * @default {
             *       "is_financial_advice": false,
             *       "text": "Educational and general in nature. These figures score a company against a fixed checklist and do not predict price movements. Nothing here is financial advice, and no checklist guarantees profit or protects against loss. Consider a licensed financial advisor for your own situation."
             *     }
             */
            disclaimer: components["schemas"]["Disclaimer"];
            /**
             * Horizon Note
             * @default Technical readings help with timing, not with what to own. Treat them as context alongside the fundamentals, never as a signal on their own.
             */
            horizon_note: string;
            /** Last Close */
            last_close: number;
            moving_average_position: components["schemas"]["MovingAveragePosition"];
            moving_averages: components["schemas"]["IndicatorReading"];
            rsi: components["schemas"]["IndicatorReading"];
            rsi_zone: components["schemas"]["RsiZone"];
            /** Sessions Analysed */
            sessions_analysed: number;
            /** Symbol */
            symbol: string;
            trend: components["schemas"]["IndicatorReading"];
            trend_direction: components["schemas"]["TrendDirection"];
            volume: components["schemas"]["IndicatorReading"];
            volume_confirmation: components["schemas"]["VolumeConfirmation"];
        };
        /**
         * TimeHorizon
         * @description Investor's intended holding period (guide section 1).
         * @enum {string}
         */
        TimeHorizon: "short_term" | "medium_term" | "long_term";
        /**
         * TradeCreate
         * @description Record an executed trade.
         */
        TradeCreate: {
            /**
             * Executed At
             * @description Defaults to now. Accepts a past date for back-filled trades.
             */
            executed_at?: string | null;
            /**
             * Fees
             * @description Brokerage, CDC and taxes.
             * @default 0
             */
            fees: number | string;
            /** Note */
            note?: string | null;
            /**
             * Plan Id
             * @description The plan this trade acts on, if there is one.
             */
            plan_id?: number | null;
            /**
             * Price
             * @description Price per share, excluding fees.
             */
            price: number | string;
            /** Quantity */
            quantity: number | string;
            side: components["schemas"]["TradeSide"];
            /** Symbol */
            symbol: string;
        };
        /**
         * TradePlanCreate
         * @description Start a plan for a company.
         *
         *     Only the symbol is required: the guide's flow is to open a plan and work
         *     through the checklist, so demanding a complete plan up front would push users
         *     into filling it in somewhere else and pasting the result.
         */
        TradePlanCreate: {
            /** Intended Amount */
            intended_amount?: number | string | null;
            /** Invalidation Note */
            invalidation_note?: string | null;
            /** Profit Target Pct */
            profit_target_pct?: number | string | null;
            /** Stop Loss Pct */
            stop_loss_pct?: number | string | null;
            /** Symbol */
            symbol: string;
            /** Thesis */
            thesis?: string | null;
        };
        /**
         * TradePlanDetail
         * @description A single plan, including its review journal.
         *
         *     Separate from :class:`TradePlanRead` so the list endpoint does not load every
         *     plan's full review history just to render a table.
         */
        TradePlanDetail: {
            /** Checklist */
            checklist: components["schemas"]["ChecklistItemRead"][];
            /** Committed At */
            committed_at?: string | null;
            /** Company Id */
            company_id: number;
            /** Company Name */
            company_name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Intended Amount */
            intended_amount?: string | null;
            /** Invalidation Note */
            invalidation_note?: string | null;
            /** Last Reviewed At */
            last_reviewed_at?: string | null;
            position_sizing?: components["schemas"]["PositionSizingCheck"] | null;
            /** Profit Target Pct */
            profit_target_pct?: string | null;
            readiness: components["schemas"]["TradePlanReadiness"];
            /** Reviews */
            reviews?: components["schemas"]["PlanReviewRead"][];
            status: components["schemas"]["TradePlanStatus"];
            /** Stop Loss Pct */
            stop_loss_pct?: string | null;
            /** Symbol */
            symbol: string;
            /** Thesis */
            thesis?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * TradePlanRead
         * @description A plan, with everything the UI needs to render and act on it.
         */
        TradePlanRead: {
            /** Checklist */
            checklist: components["schemas"]["ChecklistItemRead"][];
            /** Committed At */
            committed_at?: string | null;
            /** Company Id */
            company_id: number;
            /** Company Name */
            company_name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Intended Amount */
            intended_amount?: string | null;
            /** Invalidation Note */
            invalidation_note?: string | null;
            /** Last Reviewed At */
            last_reviewed_at?: string | null;
            position_sizing?: components["schemas"]["PositionSizingCheck"] | null;
            /** Profit Target Pct */
            profit_target_pct?: string | null;
            readiness: components["schemas"]["TradePlanReadiness"];
            status: components["schemas"]["TradePlanStatus"];
            /** Stop Loss Pct */
            stop_loss_pct?: string | null;
            /** Symbol */
            symbol: string;
            /** Thesis */
            thesis?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * TradePlanReadiness
         * @description Why a plan can or cannot be committed to.
         *
         *     Presented as explicit blocking reasons rather than a single boolean so the UI
         *     can tell the user exactly what is missing instead of greying out a button.
         */
        TradePlanReadiness: {
            /**
             * Advisory Notes
             * @description Concerns that do not block committing, e.g. a thin invalidation note.
             */
            advisory_notes?: string[];
            /** Blocking Reasons */
            blocking_reasons?: string[];
            /** Can Commit */
            can_commit: boolean;
            /** Checklist Complete */
            checklist_complete: boolean;
            /** Failed Items */
            failed_items?: string[];
            /** Has Exit Rules */
            has_exit_rules: boolean;
            /** Unanswered Items */
            unanswered_items?: string[];
        };
        /**
         * TradePlanReviewCreate
         * @description Record a thesis check-in (guide section 6).
         *
         *     The note is mandatory. A review that records only a timestamp silences the
         *     THESIS_REVIEW_DUE alert without the user having actually re-examined
         *     anything, which would make the alert worse than useless.
         */
        TradePlanReviewCreate: {
            /**
             * Note
             * @description What you re-checked, and whether the original reason to own it still holds.
             */
            note: string;
            /**
             * Thesis Still Valid
             * @default true
             */
            thesis_still_valid: boolean;
        };
        /**
         * TradePlanStatus
         * @description Lifecycle of a pre-commitment plan (guide sections 5 and 6).
         * @enum {string}
         */
        TradePlanStatus: "draft" | "ready" | "executed" | "abandoned" | "closed";
        /**
         * TradePlanUpdate
         * @description Patch a draft plan.
         *
         *     Every field is optional, and ``None`` means "not supplied" rather than "clear
         *     it". Clearing an exit rule that has already been committed to is exactly the
         *     in-the-moment decision the guide warns against, so it is not offered as a
         *     side effect of an edit.
         */
        TradePlanUpdate: {
            /** Comfortable With Drawdown */
            comfortable_with_drawdown?: boolean | null;
            /** Debt Manageable Vs Peers */
            debt_manageable_vs_peers?: boolean | null;
            /** Intended Amount */
            intended_amount?: number | string | null;
            /** Invalidation Note */
            invalidation_note?: string | null;
            /** Position Size Appropriate */
            position_size_appropriate?: boolean | null;
            /** Profit Target Pct */
            profit_target_pct?: number | string | null;
            /** Revenue And Profit Healthy */
            revenue_and_profit_healthy?: boolean | null;
            /** Stop Loss Pct */
            stop_loss_pct?: number | string | null;
            /** Thesis */
            thesis?: string | null;
            /** Understands Business */
            understands_business?: boolean | null;
        };
        /**
         * TradeRead
         * @description A recorded trade.
         */
        TradeRead: {
            /** Company Name */
            company_name: string;
            /**
             * Executed At
             * Format: date-time
             */
            executed_at: string;
            /** Fees */
            fees: string;
            /** Gross Value */
            gross_value: string;
            /** Id */
            id: number;
            /**
             * Net Cash Flow
             * @description Signed cash effect: negative for a buy, positive for a sell.
             */
            net_cash_flow: string;
            /** Note */
            note?: string | null;
            /** Plan Id */
            plan_id?: number | null;
            /** Price */
            price: string;
            /** Quantity */
            quantity: string;
            side: components["schemas"]["TradeSide"];
            /** Symbol */
            symbol: string;
        };
        /**
         * TradeSide
         * @description Direction of an executed trade.
         * @enum {string}
         */
        TradeSide: "buy" | "sell";
        /**
         * TrendDirection
         * @description Price trend classification over a lookback window.
         * @enum {string}
         */
        TrendDirection: "uptrend" | "downtrend" | "sideways" | "unknown";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VolumeConfirmation
         * @description Whether the latest price move is backed by above-average volume.
         * @enum {string}
         */
        VolumeConfirmation: "confirmed" | "unconfirmed" | "unknown";
        /**
         * WatchlistItemCreate
         * @description Add a company to the watchlist.
         *
         *     ``research_note`` is required with a real minimum length. The guide's first
         *     listed mistake is chasing hype, and the cheapest available guard is making
         *     the user articulate why they are watching something before the app will
         *     track it.
         */
        WatchlistItemCreate: {
            /**
             * Research Note
             * @description Why this company is worth watching, in your own words.
             */
            research_note: string;
            /** Symbol */
            symbol: string;
            /**
             * Target Entry Price
             * @description Price at or below which you would consider buying.
             */
            target_entry_price?: number | string | null;
        };
        /**
         * WatchlistItemRead
         * @description A watched company with a current price snapshot.
         */
        WatchlistItemRead: {
            /** Company Id */
            company_id: number;
            /** Company Name */
            company_name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Distance To Target Pct */
            distance_to_target_pct?: string | null;
            /**
             * Entry Price Reached
             * @default false
             */
            entry_price_reached: boolean;
            /**
             * Has Trade Plan
             * @default false
             */
            has_trade_plan: boolean;
            /** Id */
            id: number;
            /** Last Close */
            last_close?: string | null;
            /** Last Close Date */
            last_close_date?: string | null;
            /** Research Note */
            research_note?: string | null;
            sector: components["schemas"]["Sector"];
            /** Sector Label */
            sector_label: string;
            /** Symbol */
            symbol: string;
            /** Target Entry Price */
            target_entry_price?: string | null;
        };
        /**
         * WatchlistItemUpdate
         * @description Revise a watchlist entry.
         */
        WatchlistItemUpdate: {
            /** Research Note */
            research_note?: string | null;
            /** Target Entry Price */
            target_entry_price?: number | string | null;
        };
        /**
         * YearValue
         * @description A single fiscal-year observation used to build a metric's history.
         */
        YearValue: {
            /** Fiscal Year */
            fiscal_year: number;
            /** Value */
            value?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    sync_market_data_api_v1_admin_market_data_sync_post: {
        parameters: {
            query?: {
                /** @description Refresh a single symbol instead of everything. */
                symbol?: string | null;
                /** @description Price sessions to load per company. */
                sessions?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResultRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_alerts_api_v1_alerts_get: {
        parameters: {
            query?: {
                /** @description Include alerts you have already dismissed. */
                include_acknowledged?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    acknowledge_all_alerts_api_v1_alerts_acknowledge_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
        };
    };
    evaluate_alerts_api_v1_alerts_evaluate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertEvaluationResult"];
                };
            };
        };
    };
    acknowledge_alert_api_v1_alerts__alert_id__acknowledge_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Alert id. */
                alert_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRead"];
                };
            };
            /** @description Alert not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_companies_api_v1_companies_get: {
        parameters: {
            query?: {
                /** @description Restrict results to one PSX sector. */
                sector?: components["schemas"]["Sector"] | null;
                /** @description Match against symbol or company name. */
                search?: string | null;
                /** @description Rows per page. */
                limit?: number;
                /** @description Rows to skip. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of companies with their latest stored close. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_CompanySummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_company_api_v1_companies__symbol__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description PSX ticker symbol, e.g. OGDC. Case-insensitive. */
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyDetail"];
                };
            };
            /** @description Unknown symbol. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_fundamentals_api_v1_companies__symbol__fundamentals_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description PSX ticker symbol, e.g. OGDC. Case-insensitive. */
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FundamentalsReport"];
                };
            };
            /** @description Unknown symbol. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No financial statements are stored for this company. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_price_history_api_v1_companies__symbol__prices_get: {
        parameters: {
            query?: {
                /** @description Number of most recent sessions to return. */
                sessions?: number;
            };
            header?: never;
            path: {
                /** @description PSX ticker symbol, e.g. OGDC. Case-insensitive. */
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceHistoryRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_technicals_api_v1_companies__symbol__technicals_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description PSX ticker symbol, e.g. OGDC. Case-insensitive. */
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TechnicalReport"];
                };
            };
            /** @description Unknown symbol. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not enough price history for a technical reading. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthRead"];
                };
            };
        };
    };
    metadata_api_v1_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetadataRead"];
                };
            };
        };
    };
    list_plans_api_v1_plans_get: {
        parameters: {
            query?: {
                /** @description Restrict results to one plan status. */
                plan_status?: components["schemas"]["TradePlanStatus"] | null;
                /** @description Rows per page. */
                limit?: number;
                /** @description Rows to skip. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_TradePlanRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_plan_api_v1_plans_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TradePlanCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradePlanDetail"];
                };
            };
            /** @description Unknown symbol. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The plan is not in a state that allows this. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_plan_api_v1_plans__plan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Trade plan id. */
                plan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradePlanDetail"];
                };
            };
            /** @description Plan not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_plan_api_v1_plans__plan_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Trade plan id. */
                plan_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TradePlanUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradePlanDetail"];
                };
            };
            /** @description Plan not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The plan is not in a state that allows this. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    abandon_plan_api_v1_plans__plan_id__abandon_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Trade plan id. */
                plan_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Body_abandon_plan_api_v1_plans__plan_id__abandon_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradePlanDetail"];
                };
            };
            /** @description Plan not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The plan is not in a state that allows this. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_plan_api_v1_plans__plan_id__close_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Trade plan id. */
                plan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradePlanDetail"];
                };
            };
            /** @description Plan not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The plan is not in a state that allows this. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    commit_plan_api_v1_plans__plan_id__commit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Trade plan id. */
                plan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradePlanDetail"];
                };
            };
            /** @description Plan not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The plan is not in a state that allows this. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The checklist is incomplete or the exit rules are missing. The response lists every blocking reason. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    record_review_api_v1_plans__plan_id__reviews_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Trade plan id. */
                plan_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TradePlanReviewCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradePlanDetail"];
                };
            };
            /** @description Plan not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The plan is not in a state that allows this. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_portfolio_api_v1_portfolio_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Holdings, sector allocation and concentration warnings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioRead"];
                };
            };
        };
    };
    list_trades_api_v1_portfolio_trades_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradeRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_trade_api_v1_portfolio_trades_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TradeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradeRead"];
                };
            };
            /** @description Unknown symbol. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Selling more shares than are held, or an invalid plan reference. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_profile_api_v1_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestorProfileRead"];
                };
            };
            /** @description No profile has been written yet - the client should prompt for one. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    upsert_profile_api_v1_profile_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvestorProfileUpsert"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestorProfileRead"];
                };
            };
            /** @description Limits are incoherent, e.g. a position cap above the sector cap. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_watchlist_api_v1_watchlist_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistItemRead"][];
                };
            };
        };
    };
    add_watchlist_item_api_v1_watchlist_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistItemCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistItemRead"];
                };
            };
            /** @description Unknown symbol. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Already on the watchlist. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_watchlist_item_api_v1_watchlist__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Watchlist entry id. */
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Entry not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_watchlist_item_api_v1_watchlist__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Watchlist entry id. */
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistItemUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistItemRead"];
                };
            };
            /** @description Entry not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
