"""Declarative base and shared column mixins.

Two things are centralised here on purpose:

1. **A constraint naming convention.** Without it, SQLite and Postgres invent
   different names for the same index and Alembic autogenerate produces noisy,
   non-reversible migrations.
2. **Timestamp defaults.** ``created_at``/``updated_at`` are generated by the
   database (``func.now()``), not by Python, so rows written by a migration or
   a psql session are stamped identically to rows written by the API.
"""

from __future__ import annotations

import enum
from datetime import date, datetime
from decimal import Decimal
from typing import Annotated, Any, ClassVar

from sqlalchemy import Date, DateTime, Dialect, MetaData, Numeric, String, TypeDecorator, func
from sqlalchemy import Enum as SAEnum
from sqlalchemy.orm import DeclarativeBase, Mapped, declared_attr, mapped_column

from app.core.clock import as_utc


class UtcDateTime(TypeDecorator[datetime]):
    """Timestamp column that is always timezone-aware UTC in Python.

    SQLite has no timestamp type: SQLAlchemy stores a string and hands back a
    *naive* ``datetime``, while Postgres returns an aware one. Without this
    decorator the same comparison (``plan.last_reviewed_at < cutoff``) works in
    production and raises ``TypeError: can't compare offset-naive and
    offset-aware datetimes`` on a developer's SQLite database - or worse, the
    reverse.

    Values are normalised to UTC on the way in and re-tagged as UTC on the way
    out, so application code never has to ask which dialect it is talking to.
    """

    impl = DateTime(timezone=True)
    cache_ok = True

    def process_bind_param(self, value: datetime | None, dialect: Dialect) -> datetime | None:
        return None if value is None else as_utc(value)

    def process_result_value(self, value: datetime | None, dialect: Dialect) -> datetime | None:
        return None if value is None else as_utc(value)


# ---------------------------------------------------------------------------
# Column type aliases
#
# Money is Decimal, never float: a share price must round-trip exactly and
# cost-basis arithmetic must not accumulate binary rounding error. Declaring the
# precision once, here, stops the same figure being stored as Numeric(18, 4) in
# one table and Numeric(12, 2) in another.
# ---------------------------------------------------------------------------

#: Currency amount in PKR. 18 digits total / 4 decimals covers both a fractional
#: share price and a multi-billion-rupee revenue line.
Money = Annotated[Decimal, mapped_column(Numeric(18, 4))]

#: Ratio or percentage persisted for audit (e.g. a plan's stop-loss percentage).
Ratio = Annotated[Decimal, mapped_column(Numeric(10, 4))]

#: PSX ticker symbol, e.g. "OGDC". Upper-cased by the service layer.
TickerSymbol = Annotated[str, mapped_column(String(16))]


def enum_column(enum_cls: type[enum.Enum], *, length: int = 48) -> SAEnum:
    """Build a VARCHAR-backed column type for a Python enum.

    Deliberately **not** a native Postgres ``ENUM``: adding a sector or an alert
    kind would then require an ``ALTER TYPE`` migration and a deploy ordering
    dance. ``values_callable`` stores the lower-case member *value*
    (``"commercial_banks"``) rather than the member *name*, so the stored data
    matches what the JSON API exposes and is readable in a psql session.

    ``create_constraint`` stays at its default of ``False``: the application is
    the authority on the allowed vocabulary, and a CHECK constraint here would
    reintroduce the migration cost we are avoiding.
    """
    return SAEnum(
        enum_cls,
        native_enum=False,
        length=length,
        values_callable=lambda cls: [member.value for member in cls],
        validate_strings=True,
    )


#: ``ix`` / ``uq`` / ``ck`` / ``fk`` / ``pk`` templates - see module docstring.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Base class for every ORM model."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)

    #: Default SQL type for each Python annotation. Keeps model definitions
    #: declarative (``Mapped[Decimal]``) instead of repeating ``Numeric(18, 4)``,
    #: and guarantees every timestamp is timezone-aware on Postgres.
    type_annotation_map: ClassVar[dict[Any, Any]] = {
        Decimal: Numeric(18, 4),
        datetime: UtcDateTime(),
        date: Date(),
        str: String(255),
    }

    def __repr__(self) -> str:  # pragma: no cover - debugging aid only
        identifier = getattr(self, "id", None)
        return f"<{type(self).__name__} id={identifier}>"


class TimestampMixin:
    """Adds server-generated ``created_at`` / ``updated_at`` columns."""

    @declared_attr
    @classmethod
    def created_at(cls) -> Mapped[datetime]:
        return mapped_column(
            server_default=func.now(),
            nullable=False,
            doc="UTC timestamp set by the database when the row was inserted.",
        )

    @declared_attr
    @classmethod
    def updated_at(cls) -> Mapped[datetime]:
        return mapped_column(
            server_default=func.now(),
            onupdate=func.now(),
            nullable=False,
            doc="UTC timestamp refreshed by SQLAlchemy on every UPDATE.",
        )
