"""initial schema

Revision ID: a16572f89b2a
Revises:
Created: 2026-08-18 13:57:41.765222+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a16572f89b2a"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "sector",
            sa.Enum(
                "commercial_banks",
                "cement",
                "oil_and_gas",
                "fertilizer",
                "food_and_personal_care",
                "power_generation",
                "textile_composite",
                "automobile_assembler",
                "technology_and_communication",
                "pharmaceuticals",
                "chemical",
                "other",
                name="sector",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("business_summary", sa.Text(), nullable=True),
        sa.Column("website", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_companies")),
    )
    with op.batch_alter_table("companies", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_companies_sector"), ["sector"], unique=False)
        batch_op.create_index(batch_op.f("ix_companies_symbol"), ["symbol"], unique=True)

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    op.create_table(
        "alerts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum(
                "profit_target_reached",
                "stop_loss_breached",
                "thesis_review_due",
                "position_concentration",
                "sector_concentration",
                "watchlist_entry_price_reached",
                "fundamental_red_flag",
                name="alertkind",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.Enum(
                "info", "warning", "critical", name="alertseverity", native_enum=False, length=48
            ),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("context", sa.JSON(), nullable=False),
        sa.Column("dedupe_key", sa.String(length=200), nullable=False),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_alerts_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_alerts_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alerts")),
        sa.UniqueConstraint("user_id", "dedupe_key", name="user_dedupe_key"),
    )
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_alerts_company_id"), ["company_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_alerts_kind"), ["kind"], unique=False)
        batch_op.create_index(
            "ix_alerts_user_acknowledged", ["user_id", "acknowledged_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_alerts_user_id"), ["user_id"], unique=False)

    op.create_table(
        "annual_financials",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("fiscal_year", sa.Integer(), nullable=False),
        sa.Column("revenue", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("net_profit", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("eps", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("total_assets", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("total_equity", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("total_debt", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("operating_cash_flow", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("capital_expenditure", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("dividend_per_share", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("shares_outstanding", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("source", sa.String(length=200), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "fiscal_year BETWEEN 1990 AND 2100", name=op.f("ck_annual_financials_fiscal_year_range")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_annual_financials_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_annual_financials")),
        sa.UniqueConstraint("company_id", "fiscal_year", name="company_fiscal_year"),
    )
    with op.batch_alter_table("annual_financials", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_annual_financials_company_id"), ["company_id"], unique=False
        )
        batch_op.create_index(
            "ix_annual_financials_company_year", ["company_id", "fiscal_year"], unique=False
        )

    op.create_table(
        "investor_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "time_horizon",
            sa.Enum(
                "short_term",
                "medium_term",
                "long_term",
                name="timehorizon",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column(
            "risk_tolerance",
            sa.Enum(
                "conservative",
                "moderate",
                "aggressive",
                name="risktolerance",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("drawdown_tolerance_pct", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("investable_capital", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("max_position_pct", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("max_sector_pct", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("emergency_fund_in_place", sa.Boolean(), nullable=False),
        sa.Column("investing_borrowed_money", sa.Boolean(), nullable=False),
        sa.Column("review_interval_days", sa.Integer(), nullable=False),
        sa.Column("goals_note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "drawdown_tolerance_pct >= 0 AND drawdown_tolerance_pct <= 100",
            name=op.f("ck_investor_profiles_drawdown_tolerance_pct_range"),
        ),
        sa.CheckConstraint(
            "max_position_pct > 0 AND max_position_pct <= 100",
            name=op.f("ck_investor_profiles_max_position_pct_range"),
        ),
        sa.CheckConstraint(
            "max_sector_pct > 0 AND max_sector_pct <= 100",
            name=op.f("ck_investor_profiles_max_sector_pct_range"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_investor_profiles_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_investor_profiles")),
    )
    with op.batch_alter_table("investor_profiles", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_investor_profiles_user_id"), ["user_id"], unique=True)

    op.create_table(
        "price_bars",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("open", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("high", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("low", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("close", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("volume", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("high >= low", name=op.f("ck_price_bars_high_ge_low")),
        sa.CheckConstraint("volume >= 0", name=op.f("ck_price_bars_volume_non_negative")),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_price_bars_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_price_bars")),
        sa.UniqueConstraint("company_id", "trade_date", name="company_trade_date"),
    )
    with op.batch_alter_table("price_bars", schema=None) as batch_op:
        batch_op.create_index(
            "ix_price_bars_company_date", ["company_id", "trade_date"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_price_bars_company_id"), ["company_id"], unique=False)

    op.create_table(
        "trade_plans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "ready",
                "executed",
                "abandoned",
                "closed",
                name="tradeplanstatus",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("understands_business", sa.Boolean(), nullable=True),
        sa.Column("revenue_and_profit_healthy", sa.Boolean(), nullable=True),
        sa.Column("debt_manageable_vs_peers", sa.Boolean(), nullable=True),
        sa.Column("comfortable_with_drawdown", sa.Boolean(), nullable=True),
        sa.Column("position_size_appropriate", sa.Boolean(), nullable=True),
        sa.Column("thesis", sa.Text(), nullable=True),
        sa.Column("invalidation_note", sa.Text(), nullable=True),
        sa.Column("intended_amount", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("profit_target_pct", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("stop_loss_pct", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("committed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "profit_target_pct IS NULL OR profit_target_pct > 0",
            name=op.f("ck_trade_plans_profit_target_pct_positive"),
        ),
        sa.CheckConstraint(
            "stop_loss_pct IS NULL OR (stop_loss_pct > 0 AND stop_loss_pct < 100)",
            name=op.f("ck_trade_plans_stop_loss_pct_range"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_trade_plans_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_trade_plans_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trade_plans")),
    )
    with op.batch_alter_table("trade_plans", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_trade_plans_company_id"), ["company_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_trade_plans_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_trade_plans_user_id"), ["user_id"], unique=False)

    op.create_table(
        "watchlist_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("target_entry_price", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("research_note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_watchlist_items_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_watchlist_items_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_watchlist_items")),
        sa.UniqueConstraint("user_id", "company_id", name="user_company"),
    )
    with op.batch_alter_table("watchlist_items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_watchlist_items_company_id"), ["company_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_watchlist_items_user_id"), ["user_id"], unique=False)

    op.create_table(
        "plan_reviews",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("thesis_still_valid", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["trade_plans.id"],
            name=op.f("fk_plan_reviews_plan_id_trade_plans"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plan_reviews")),
    )
    with op.batch_alter_table("plan_reviews", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_plan_reviews_plan_id"), ["plan_id"], unique=False)

    op.create_table(
        "trades",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=True),
        sa.Column(
            "side",
            sa.Enum("buy", "sell", name="tradeside", native_enum=False, length=48),
            nullable=False,
        ),
        sa.Column("quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("price", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("fees", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("fees >= 0", name=op.f("ck_trades_fees_non_negative")),
        sa.CheckConstraint("price > 0", name=op.f("ck_trades_price_positive")),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_trades_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_trades_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["trade_plans.id"],
            name=op.f("fk_trades_plan_id_trade_plans"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_trades_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trades")),
    )
    with op.batch_alter_table("trades", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_trades_company_id"), ["company_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_trades_plan_id"), ["plan_id"], unique=False)
        batch_op.create_index(
            "ix_trades_user_company_executed",
            ["user_id", "company_id", "executed_at"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_trades_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the change."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("trades", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_trades_user_id"))
        batch_op.drop_index("ix_trades_user_company_executed")
        batch_op.drop_index(batch_op.f("ix_trades_plan_id"))
        batch_op.drop_index(batch_op.f("ix_trades_company_id"))

    op.drop_table("trades")
    with op.batch_alter_table("plan_reviews", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_plan_reviews_plan_id"))

    op.drop_table("plan_reviews")
    with op.batch_alter_table("watchlist_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_watchlist_items_user_id"))
        batch_op.drop_index(batch_op.f("ix_watchlist_items_company_id"))

    op.drop_table("watchlist_items")
    with op.batch_alter_table("trade_plans", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_trade_plans_user_id"))
        batch_op.drop_index(batch_op.f("ix_trade_plans_status"))
        batch_op.drop_index(batch_op.f("ix_trade_plans_company_id"))

    op.drop_table("trade_plans")
    with op.batch_alter_table("price_bars", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_price_bars_company_id"))
        batch_op.drop_index("ix_price_bars_company_date")

    op.drop_table("price_bars")
    with op.batch_alter_table("investor_profiles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_investor_profiles_user_id"))

    op.drop_table("investor_profiles")
    with op.batch_alter_table("annual_financials", schema=None) as batch_op:
        batch_op.drop_index("ix_annual_financials_company_year")
        batch_op.drop_index(batch_op.f("ix_annual_financials_company_id"))

    op.drop_table("annual_financials")
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_alerts_user_id"))
        batch_op.drop_index("ix_alerts_user_acknowledged")
        batch_op.drop_index(batch_op.f("ix_alerts_kind"))
        batch_op.drop_index(batch_op.f("ix_alerts_company_id"))

    op.drop_table("alerts")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    with op.batch_alter_table("companies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_companies_symbol"))
        batch_op.drop_index(batch_op.f("ix_companies_sector"))

    op.drop_table("companies")
    # ### end Alembic commands ###
