"""Domain enumerations shared by ORM models, DTOs and the analysis engines.

These live in one module (rather than next to the models) because the analysis
package must stay importable without pulling in SQLAlchemy, and the API schemas
must describe the exact same vocabulary the database stores.

Naming discipline: this product is decision *support*, not advice. Nothing here
is allowed to be called BUY / SELL / STRONG_BUY. Metric outcomes use
:class:`MetricVerdict` (a quality judgement about a number) and technical
readings use descriptive states (``UPTREND``, ``OVERBOUGHT``) - never actions.
"""

from __future__ import annotations

from enum import StrEnum


class MetricVerdict(StrEnum):
    """Quality of a single fundamental metric against the guide's criteria."""

    STRONG = "strong"
    ADEQUATE = "adequate"
    WEAK = "weak"
    #: Not enough history (or a missing input) to judge - never treated as "bad".
    INSUFFICIENT_DATA = "insufficient_data"


class TrendDirection(StrEnum):
    """Price trend classification over a lookback window."""

    UPTREND = "uptrend"
    DOWNTREND = "downtrend"
    SIDEWAYS = "sideways"
    UNKNOWN = "unknown"


class RsiZone(StrEnum):
    """Relative Strength Index bands as described in the guide (30 / 70)."""

    OVERSOLD = "oversold"
    NEUTRAL = "neutral"
    OVERBOUGHT = "overbought"
    UNKNOWN = "unknown"


class MovingAveragePosition(StrEnum):
    """Where price sits relative to the 50-day and 200-day moving averages."""

    ABOVE_BOTH = "above_both"
    MIXED = "mixed"
    BELOW_BOTH = "below_both"
    UNKNOWN = "unknown"


class VolumeConfirmation(StrEnum):
    """Whether the latest price move is backed by above-average volume."""

    CONFIRMED = "confirmed"
    UNCONFIRMED = "unconfirmed"
    UNKNOWN = "unknown"


class TimeHorizon(StrEnum):
    """Investor's intended holding period (guide section 1)."""

    #: Under a year - the guide calls this trading, not investing.
    SHORT_TERM = "short_term"
    #: 1-3 years.
    MEDIUM_TERM = "medium_term"
    #: 3-5+ years, the horizon the fundamentals checklist is designed for.
    LONG_TERM = "long_term"


class RiskTolerance(StrEnum):
    """Self-assessed tolerance for drawdown."""

    CONSERVATIVE = "conservative"
    MODERATE = "moderate"
    AGGRESSIVE = "aggressive"


class TradePlanStatus(StrEnum):
    """Lifecycle of a pre-commitment plan (guide sections 5 and 6)."""

    #: Being filled in; checklist incomplete.
    DRAFT = "draft"
    #: Checklist complete and exit rules set - eligible to act on.
    READY = "ready"
    #: The buy happened; the plan now governs the open position.
    EXECUTED = "executed"
    #: Abandoned before buying (thesis failed the checklist).
    ABANDONED = "abandoned"
    #: Position fully exited; kept for the decision journal.
    CLOSED = "closed"


class TradeSide(StrEnum):
    """Direction of an executed trade."""

    BUY = "buy"
    SELL = "sell"


class AlertKind(StrEnum):
    """Reasons the portfolio monitor raises an alert.

    Each is a *pre-committed rule the user wrote themselves* firing - not a
    recommendation generated by the system.
    """

    PROFIT_TARGET_REACHED = "profit_target_reached"
    STOP_LOSS_BREACHED = "stop_loss_breached"
    THESIS_REVIEW_DUE = "thesis_review_due"
    POSITION_CONCENTRATION = "position_concentration"
    SECTOR_CONCENTRATION = "sector_concentration"
    WATCHLIST_ENTRY_PRICE_REACHED = "watchlist_entry_price_reached"
    FUNDAMENTAL_RED_FLAG = "fundamental_red_flag"


class AlertSeverity(StrEnum):
    """How loudly an alert should be surfaced in the UI."""

    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


class Sector(StrEnum):
    """PSX sectors used for peer comparison and diversification checks.

    Deliberately coarse: the guide's advice is to compare P/E and debt against
    peers "in the same sector" and to diversify across sectors such as banks,
    cement, oil & gas, fertilizer and consumer goods.
    """

    COMMERCIAL_BANKS = "commercial_banks"
    CEMENT = "cement"
    OIL_AND_GAS = "oil_and_gas"
    FERTILIZER = "fertilizer"
    FOOD_AND_PERSONAL_CARE = "food_and_personal_care"
    POWER_GENERATION = "power_generation"
    TEXTILE_COMPOSITE = "textile_composite"
    AUTOMOBILE_ASSEMBLER = "automobile_assembler"
    TECHNOLOGY_AND_COMMUNICATION = "technology_and_communication"
    PHARMACEUTICALS = "pharmaceuticals"
    CHEMICAL = "chemical"
    OTHER = "other"


#: Human-readable labels. Kept server-side so the API is self-describing and the
#: frontend never hard-codes a second copy of the vocabulary.
SECTOR_LABELS: dict[Sector, str] = {
    Sector.COMMERCIAL_BANKS: "Commercial Banks",
    Sector.CEMENT: "Cement",
    Sector.OIL_AND_GAS: "Oil & Gas",
    Sector.FERTILIZER: "Fertilizer",
    Sector.FOOD_AND_PERSONAL_CARE: "Food & Personal Care",
    Sector.POWER_GENERATION: "Power Generation & Distribution",
    Sector.TEXTILE_COMPOSITE: "Textile Composite",
    Sector.AUTOMOBILE_ASSEMBLER: "Automobile Assembler",
    Sector.TECHNOLOGY_AND_COMMUNICATION: "Technology & Communication",
    Sector.PHARMACEUTICALS: "Pharmaceuticals",
    Sector.CHEMICAL: "Chemical",
    Sector.OTHER: "Other",
}
